export const TRANSACTION_STATUSES = {
  ITEM_HOLD: 'ITEM_HOLD',
  PATRON_HOLD: 'PATRON_HOLD',
  LOCAL_HOLD: 'LOCAL_HOLD',
  TRANSFER: 'TRANSFER',
  ITEM_SHIPPED: 'ITEM_SHIPPED',
  ITEM_IN_TRANSIT: 'ITEM_IN_TRANSIT',
  ITEM_RECEIVED: 'ITEM_RECEIVED',
  RECEIVE_UNANNOUNCED: 'RECEIVE_UNANNOUNCED',
  RETURN_UNCIRCULATED: 'RETURN_UNCIRCULATED',
  LOCAL_CHECKOUT: 'LOCAL_CHECKOUT',
  CANCEL_REQUEST: 'CANCEL_REQUEST',
  BORROWING_SITE_CANCEL: 'BORROWING_SITE_CANCEL',
  BORROWER_RENEW: 'BORROWER_RENEW',
  CLAIMS_RETURNED: 'CLAIMS_RETURNED',
  RECALL: 'RECALL',
  FINAL_CHECKIN: 'FINAL_CHECKIN',
};

export const TRANSACTION_FIELDS = {
  ID: 'id',
  TIME: 'time',
  TYPE: 'type',
  ITEM_TITLE: 'itemTitle',
  PATRON_NAME: 'patronName',
  STATUS: 'status',
};

export const TRANSACTION_LIST_DEFAULT_SORT_FIELD = TRANSACTION_FIELDS.TIME;

export const RESULT_COUNT_INCREMENT = 100;
